package com.porarri.yamabikochat.ui.theme

import androidx.compose.ui.graphics.Color

// Fallback palette used when Dynamic Color is disabled.
val YamabikoLightPrimary = Color(0xFF5A5FCF)
val YamabikoLightOnPrimary = Color(0xFFFFFFFF)
val YamabikoLightPrimaryContainer = Color(0xFFDEE0FF)
val YamabikoLightOnPrimaryContainer = Color(0xFF1B1B5E)
val YamabikoLightSecondary = Color(0xFF5D5C72)
val YamabikoLightOnSecondary = Color(0xFFFFFFFF)
val YamabikoLightSecondaryContainer = Color(0xFFE3E0F7)
val YamabikoLightOnSecondaryContainer = Color(0xFF1A1B2C)
val YamabikoLightTertiary = Color(0xFF3A6B7C)
val YamabikoLightOnTertiary = Color(0xFFFFFFFF)
val YamabikoLightTertiaryContainer = Color(0xFFCFE9F5)
val YamabikoLightOnTertiaryContainer = Color(0xFF10343E)
val YamabikoLightBackground = Color(0xFFF7F6FB)
val YamabikoLightOnBackground = Color(0xFF1C1B20)
val YamabikoLightSurface = Color(0xFFFDFBFF)
val YamabikoLightOnSurface = Color(0xFF1C1B20)
val YamabikoLightSurfaceVariant = Color(0xFFE4E1EC)
val YamabikoLightOnSurfaceVariant = Color(0xFF47464F)
val YamabikoLightOutline = Color(0xFF797780)
val YamabikoLightOutlineVariant = Color(0xFFC8C5D0)

val YamabikoDarkPrimary = Color(0xFFB8C1FF)
val YamabikoDarkOnPrimary = Color(0xFF262A7F)
val YamabikoDarkPrimaryContainer = Color(0xFF3D438E)
val YamabikoDarkOnPrimaryContainer = Color(0xFFE0E2FF)
val YamabikoDarkSecondary = Color(0xFFC7C4DD)
val YamabikoDarkOnSecondary = Color(0xFF2E2F42)
val YamabikoDarkSecondaryContainer = Color(0xFF45475B)
val YamabikoDarkOnSecondaryContainer = Color(0xFFE3E0F7)
val YamabikoDarkTertiary = Color(0xFFA8D2DF)
val YamabikoDarkOnTertiary = Color(0xFF1F343B)
val YamabikoDarkTertiaryContainer = Color(0xFF354A52)
val YamabikoDarkOnTertiaryContainer = Color(0xFFC3E9F6)
val YamabikoDarkBackground = Color(0xFF111318)
val YamabikoDarkOnBackground = Color(0xFFE3E1E7)
val YamabikoDarkSurface = Color(0xFF16181D)
val YamabikoDarkOnSurface = Color(0xFFE3E1E7)
val YamabikoDarkSurfaceVariant = Color(0xFF44454F)
val YamabikoDarkOnSurfaceVariant = Color(0xFFC6C5D0)
val YamabikoDarkOutline = Color(0xFF908F9A)
val YamabikoDarkOutlineVariant = Color(0xFF45464F)
