package com.porarri.yamabikochat.ui.settings

/**
 * Encapsulates all values required to persist settings in a single object,
 * replacing the long parameter list previously used by SettingsViewModel.saveSettings.
 */
data class SettingsUpdateRequest(
    val apiKey: String,
    val model: String,
    /**
     * Provider-specific model selections being edited in the Settings UI.
     * Keys are provider ids (e.g. GEMINI/OPENROUTER/MINIMAX/OPENAI/CODEX_AUTH/OPENAI_COMPAT/ZAI).
     */
    val providerModels: Map<String, String> = emptyMap(),
    val googleSearchEnabled: Boolean,
    val codeExecutionEnabled: Boolean,
    val urlContextEnabled: Boolean = false,
    val googleMapsEnabled: Boolean = false,
    val computerUseEnabled: Boolean = false,
    val thinkingEnabled: Boolean,
    val thinkingBudget: Int,
    val thinkingLevel: String,
    val responseMimeType: String = "",
    val responseJsonSchema: String = "",
    val functionDeclarations: String = "",
    val systemPrompt: String?,
    val systemPromptPresets: List<com.porarri.yamabikochat.data.local.SystemPromptPreset> = emptyList(),
    val selectedSystemPromptPreset: String? = null,
    val isStreamingEnabled: Boolean,
    val apiProvider: String,
    val openRouterApiKey: String,
    val openAiApiKey: String = "",
    val miniMaxApiKey: String = "",
    val zaiApiKey: String = "",
    val openAiCompatApiKey: String = "",
    val geminiApiKeyAction: ApiKeyAction = ApiKeyAction.NoChange,
    val openRouterApiKeyAction: ApiKeyAction = ApiKeyAction.NoChange,
    val openAiApiKeyAction: ApiKeyAction = ApiKeyAction.NoChange,
    val miniMaxApiKeyAction: ApiKeyAction = ApiKeyAction.NoChange,
    val zaiApiKeyAction: ApiKeyAction = ApiKeyAction.NoChange,
    val openAiCompatApiKeyAction: ApiKeyAction = ApiKeyAction.NoChange,
    val isDualModeEnabled: Boolean,
    val dualModelA: String,
    val dualModelB: String,
    val dualProviderA: String,
    val dualProviderB: String,
    val dualSplitLayout: String,
    val dualSplitRatio: Float,
    val dualSystemPromptA: String? = null,
    val dualSystemPromptB: String? = null,
    val isAutoConversationEnabled: Boolean,
    val autoModelA: String,
    val autoModelB: String,
    val autoProviderA: String,
    val autoProviderB: String,
    val autoSystemPromptA: String,
    val autoSystemPromptB: String,
    val autoMaxTurns: Int,
    val mathRenderingEnabled: Boolean,
    val dynamicColorEnabled: Boolean = true,
    val themeColor: String = "BLUE_PURPLE",
    val themeMode: String = "SYSTEM",
    val showGlobalProviderPresetsInChat: Boolean = true,
    val showGlobalProviderPresetsInChatByProvider: Map<String, Boolean> = emptyMap(),
    val preferredProviders: List<String> = emptyList(),
    val selectedQuantizations: List<String> = emptyList(),
    val maxPricePerMillionTokens: Double = 0.0,
    val allowFallbacks: Boolean = true,
    val requireParameters: Boolean = false,
    val providerSelectionMax: Int = 12,
    val providerSort: String = "price",
    val openAiBaseUrl: String = "https://api.openai.com/v1/",
    val miniMaxBaseUrl: String = "https://api.minimax.io/v1/",
    val openAiCompatPresets: List<com.porarri.yamabikochat.data.remote.OpenAiCompatPreset> = emptyList(),
    val selectedOpenAiCompatPreset: String? = null,
    val openRouterReasoningMode: String = "auto",
    val openRouterReasoningEffort: String = "",
    val openRouterReasoningExclude: Boolean = false,
    val codexUserAgentPreset: String = "ANDROID",
    val codexReasoningEnabled: Boolean = true,
    val codexReasoningEffort: String = "medium",
    val codexReasoningSummary: String = "auto",
    val codexVerbosity: String = "medium",
    val codexSupportsReasoningSummaries: Boolean = false,
    val codexShowReasoningSummary: Boolean = true,
    val codexWebSearchEnabled: Boolean = false,
    val codexWebSearchContextSize: String = "medium",
    val codexPromptCacheEnabled: Boolean = true,
    val codexPromptCacheMinLength: Int = 512,
    val codexPromptCacheType: String = "ephemeral",
    val dualOpenRouterThinkingEnabledA: Boolean? = null,
    val dualOpenRouterThinkingBudgetA: Int? = null,
    val dualOpenRouterReasoningModeA: String? = null,
    val dualOpenRouterReasoningEffortA: String? = null,
    val dualOpenRouterReasoningExcludeA: Boolean? = null,
    val dualOpenRouterThinkingEnabledB: Boolean? = null,
    val dualOpenRouterThinkingBudgetB: Int? = null,
    val dualOpenRouterReasoningModeB: String? = null,
    val dualOpenRouterReasoningEffortB: String? = null,
    val dualOpenRouterReasoningExcludeB: Boolean? = null,
    val autoOpenRouterThinkingEnabledA: Boolean? = null,
    val autoOpenRouterThinkingBudgetA: Int? = null,
    val autoOpenRouterReasoningModeA: String? = null,
    val autoOpenRouterReasoningEffortA: String? = null,
    val autoOpenRouterReasoningExcludeA: Boolean? = null,
    val autoOpenRouterThinkingEnabledB: Boolean? = null,
    val autoOpenRouterThinkingBudgetB: Int? = null,
    val autoOpenRouterReasoningModeB: String? = null,
    val autoOpenRouterReasoningEffortB: String? = null,
    val autoOpenRouterReasoningExcludeB: Boolean? = null,
    val dualGoogleSearchEnabledA: Boolean? = null,
    val dualCodeExecutionEnabledA: Boolean? = null,
    val dualUrlContextEnabledA: Boolean? = null,
    val dualGoogleMapsEnabledA: Boolean? = null,
    val dualComputerUseEnabledA: Boolean? = null,
    val dualThinkingEnabledA: Boolean? = null,
    val dualThinkingBudgetA: Int? = null,
    val dualThinkingLevelA: String? = null,
    val dualCodexReasoningEffortA: String? = null,
    val dualGoogleSearchEnabledB: Boolean? = null,
    val dualCodeExecutionEnabledB: Boolean? = null,
    val dualUrlContextEnabledB: Boolean? = null,
    val dualGoogleMapsEnabledB: Boolean? = null,
    val dualComputerUseEnabledB: Boolean? = null,
    val dualThinkingEnabledB: Boolean? = null,
    val dualThinkingBudgetB: Int? = null,
    val dualThinkingLevelB: String? = null,
    val dualCodexReasoningEffortB: String? = null,
    val autoGoogleSearchEnabledA: Boolean? = null,
    val autoCodeExecutionEnabledA: Boolean? = null,
    val autoUrlContextEnabledA: Boolean? = null,
    val autoGoogleMapsEnabledA: Boolean? = null,
    val autoComputerUseEnabledA: Boolean? = null,
    val autoThinkingEnabledA: Boolean? = null,
    val autoThinkingBudgetA: Int? = null,
    val autoThinkingLevelA: String? = null,
    val autoCodexReasoningEffortA: String? = null,
    val autoGoogleSearchEnabledB: Boolean? = null,
    val autoCodeExecutionEnabledB: Boolean? = null,
    val autoUrlContextEnabledB: Boolean? = null,
    val autoGoogleMapsEnabledB: Boolean? = null,
    val autoComputerUseEnabledB: Boolean? = null,
    val autoThinkingEnabledB: Boolean? = null,
    val autoThinkingBudgetB: Int? = null,
    val autoThinkingLevelB: String? = null,
    val autoCodexReasoningEffortB: String? = null
)
